In [ ]:
import numpy as np
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
list1=[[2,3,4],[5,6,7],[8,9,10]]
np.array(list1)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,50,8)

array([ 1,  9, 17, 25, 33, 41, 49])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [ ]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [3]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
a=np.random.rand(3,2)
a.T

array([[0.71361169, 0.86274783, 0.32487076],
       [0.89818808, 0.27826947, 0.03934547]])

In [6]:
np.random.rand(2,3)

array([[0.31286632, 0.25587805, 0.21667931],
       [0.04269371, 0.83832593, 0.68248868]])

In [7]:
np.random.randn(3,2)
##here positive and negetive are also included

array([[ 0.05932795,  0.57849918],
       [ 0.68894405, -1.26564664],
       [-0.33303361, -0.62056642]])

In [8]:
np.random.randint(34,56)

48

In [10]:
np.random.randint(20,56,6)
##6 random numbers bet 20,56

array([28, 53, 23, 49, 49, 38])

In [21]:
arr=np.array([23,89,12,0,9])

arr.argmax()

1

In [22]:
arr.argmin()

3

In [23]:
arr.max()

89

In [24]:
arr[-2]

0

In [27]:
arr[1:4]

array([89, 12,  0])

In [28]:
arr[:]

array([23, 89, 12,  0,  9])

In [30]:
arr[:]=99999999

In [31]:
arr

array([99999999, 99999999, 99999999, 99999999, 99999999])

In [32]:
arr[2:4]=100
arr

array([99999999, 99999999,      100,      100, 99999999])

2 dimensional array

In [40]:
###iniialization
mat=np.array(([50,20,23,45],[51,12,52,84],[1,444444,0,10]))
mat

array([[    50,     20,     23,     45],
       [    51,     12,     52,     84],
       [     1, 444444,      0,     10]])

In [34]:
mat[2,:]

array([ 1,  0, 10])

In [36]:
mat[:,1]

array([20, 12,  0])

In [41]:
mat[:,(2,3)]

array([[23, 45],
       [52, 84],
       [ 0, 10]])

In [42]:
np.exp(mat)

<ipython-input-42-6e1dbb3d7aba>:1: RuntimeWarning: overflow encountered in exp
  np.exp(mat)


array([[5.18470553e+21, 4.85165195e+08, 9.74480345e+09, 3.49342711e+19],
       [1.40934908e+22, 1.62754791e+05, 3.83100800e+22, 3.02507732e+36],
       [2.71828183e+00,            inf, 1.00000000e+00, 2.20264658e+04]])

In [43]:
np.sqrt(mat)

array([[  7.07106781,   4.47213595,   4.79583152,   6.70820393],
       [  7.14142843,   3.46410162,   7.21110255,   9.16515139],
       [  1.        , 666.66633333,   0.        ,   3.16227766]])

In [44]:
np.log(mat)

<ipython-input-44-c1ed3ae3dc4d>:1: RuntimeWarning: divide by zero encountered in log
  np.log(mat)


array([[ 3.91202301,  2.99573227,  3.13549422,  3.80666249],
       [ 3.93182563,  2.48490665,  3.95124372,  4.4308168 ],
       [ 0.        , 13.00457934,        -inf,  2.30258509]])

In [45]:
np.min(mat)

0

In [46]:
np.max(mat)

444444

In [47]:
np.argmax(mat)

9

In [48]:
np.square(mat)

array([[        2500,          400,          529,         2025],
       [        2601,          144,         2704,         7056],
       [           1, 197530469136,            0,          100]])

In [49]:
np.var(mat)
###variance

15086985577.0

In [50]:
np.mean(mat)

37066.0

In [51]:
np.std(mat)
###standard deviation

122829.09092311967

In [52]:
np.round(mat,decimals=3)

array([[    50,     20,     23,     45],
       [    51,     12,     52,     84],
       [     1, 444444,      0,     10]])